name: CI/CD dev Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.1'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm install
          # Проверяем установленные пакеты
          npm list --depth=0

      - name: Build project
        env:
          VITE_TPU_OAUTH_CLIENT_ID: ${{ secrets.VITE_TPU_OAUTH_CLIENT_ID }}
        run: |
          npm run build
          # Проверяем результат сборки
          ls dist

      - name: Verify build output
        run: |
          test -d dist || (echo "Директория dist не создана" && exit 1)
          test -f dist/index.html || (echo "Файл index.html отсутствует" && exit 1)

      - name: Deploy to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "~/tempAdm"
          debug: true

      - name: Verify deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Проверка логов Nginx"
            sudo tail -n 50 /var/log/nginx/error.log
            echo "Проверка доступности приложения"
            curl http://${{ secrets.HOST}}
